id: P0BE00399
initial_creation_type: input
source_metadata:
  title: Jamgön Kongtrul Lodrö Thaye Series
  language: es
  description: Works by or about the great nineteenth century master Jamgön Kongtrul
    Lodrö Thaye ('jam mgon kong sprul blo gros mtha' yas, 1813–1899), one of the pioneers
    of the Rimé movement
  volume:
    afb0aa95e40044c08e140f261cdb7589:
      title: Advice to Lhawang Tashi
      parent: Advice
    e9b20857195d424ca2828122fabdb1c0:
      title: Mahāmudrā Preliminaries, Main Part & Conclusion
      parent: Advice
    04cebc7953184f02aaf7738dc45bfaed:
      title: 'Mahāmudrā: the Swift Way to Become a Lord of Realization'
      parent: Advice
    99b2f2d01abb4b23ada0e8d286746fb7:
      title: The Kusāli's Instruction on the Nature of Mind
      parent: Advice
    5974bb94be2e4288a0de84211999d2f7:
      title: Prayer for Peace and Stability in Tibet
      parent: Aspiration Prayers
    563031363b92497c9d5761ab399ea37e:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Aspiration Prayers
    e47c981888f747f78f7eb4007cc84557:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Biography
    3ac43ae8fdff40a59cf23ee375776851:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    6beebb2df3b84994a9f2c4f1949e17da:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Biography
    3986ea407aad48ceb5294bc90847a9d8:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Calling the Guru From Afar
    e64716358c5646eda280775419832df6:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      parent: Commentaries
    95065ac90def42bb9da36278adca99c9:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Empowerment Rites
    05a1a30c326542b986c5e0ba85c23222:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Fire Offering
    816808f9c1324c95ac57244344eab2c3:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Guru Rinpoche Prayers
    0070f8e24c624876b7fe9de3bdeef88c:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Lineage Prayers
    c792c9cad5944504b10238c16d6e7ea7:
      title: A Short Supplication to Tārā
      parent: Prayers
    98cb24c49a0e41c5942071ecfb548f03:
      title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse
        Chökyi Lodrö
      parent: Prayers
    2d907faf88964dcfb9cc80dc1a5a2230:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    65b60417568a40b69857814135be389a:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Prayers
    15220bc1e5ae451394b2a4c1ebfdc26a:
      title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master
        Jamgön Kongtrul Thaye'
      parent: Prayers
    f3020f0dd5ea4c9caf5c739a8906bf37:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Prayers
    02a4240bc505429691eb528b79561b89:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Saving Lives
    8efc8bcc7c00437883746d91f0345f06:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Swift Rebirth Prayers
    dd8b8d0eba4e47179817efc86e6badf9:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Tsok
    71612cc014f04afba5420c5ca84ec660:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T23:32:21.218423'
last_modified_at: '2022-02-28T23:32:21.218426'
